name: CLA check

# check if the PR author has signed the CLA

on:
  pull_request_target:
    branches:
      - develop
      - release-*
      - js-*

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Oppiabot-mridul
        # You may pin to the exact commit or the version.
        # uses: mridul-netizen/oppiabot@20e26be61dd8944242d4f04a5e481e9575e4974b
        uses: mridul-netizen/oppiabot@test-1.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
        env:
          SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
          SHEETS_CRED: ${{ secrets.SHEETS_CRED }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
